/* homepage.js */
'use strict';

// ===== HERO SLIDER =====
function initHeroSlider() {
  const slides = document.querySelectorAll('.hero-slide');
  const dots = document.querySelectorAll('.hero-dot');
  if (!slides.length) return;
  let current = 0, timer;
  const goTo = (idx) => {
    slides[current].classList.remove('active');
    dots[current]?.classList.remove('active');
    current = (idx + slides.length) % slides.length;
    slides[current].classList.add('active');
    dots[current]?.classList.add('active');
  };
  const next = () => goTo(current + 1);
  const prev = () => goTo(current - 1);
  const startAuto = () => { timer = setInterval(next, 5500); };
  const stopAuto = () => clearInterval(timer);
  slides[0]?.classList.add('active');
  dots[0]?.classList.add('active');
  startAuto();
  document.getElementById('hero-next')?.addEventListener('click', () => { stopAuto(); next(); startAuto(); });
  document.getElementById('hero-prev')?.addEventListener('click', () => { stopAuto(); prev(); startAuto(); });
  dots.forEach((dot, i) => dot.addEventListener('click', () => { stopAuto(); goTo(i); startAuto(); }));
  let touchStartX = 0;
  const slider = document.querySelector('.hero-slider');
  slider?.addEventListener('touchstart', e => { touchStartX = e.touches[0].clientX; }, { passive: true });
  slider?.addEventListener('touchend', e => {
    const diff = touchStartX - e.changedTouches[0].clientX;
    if (Math.abs(diff) > 50) { stopAuto(); diff > 0 ? next() : prev(); startAuto(); }
  });
}

// ===== TESTIMONIALS SLIDER =====
function initTestimonialsSlider() {
  const track = document.getElementById('testimonials-track');
  if (!track) return;
  const cards = track.querySelectorAll('.testimonial-card');
  let current = 0;
  const visible = window.innerWidth >= 1024 ? 3 : window.innerWidth >= 640 ? 2 : 1;
  const move = () => {
    const card = cards[0];
    if (!card) return;
    track.style.transform = `translateX(-${current * (card.offsetWidth + 24)}px)`;
  };
  document.getElementById('test-prev')?.addEventListener('click', () => { if (current > 0) { current--; move(); } });
  document.getElementById('test-next')?.addEventListener('click', () => { if (current < cards.length - visible) { current++; move(); } });
}

// ===== QUICK VIEW =====
function openQuickView(productId) {
  const product = PRODUCTS_DATA.find(p => p.id === productId);
  if (!product) return;
  const modal = document.getElementById('quickview-modal');
  if (!modal) return;
  modal.querySelector('.quickview-gallery img').src = product.images[0];
  modal.querySelector('.quickview-info').innerHTML = `
    <button class="modal-close" onclick="closeQuickView()"><svg fill="none" stroke="currentColor" viewBox="0 0 24 24" width="20" height="20"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M6 18L18 6M6 6l12 12"/></svg></button>
    <div class="product-badges">${product.badge ? `<span class="badge">${product.badge}</span>` : ''}</div>
    <h2 class="product-name" style="font-size:1.4rem">${product.name}</h2>
    <div class="product-price-main" style="margin-bottom:20px">${formatPrice(product.price)}</div>
    <div class="variant-group"><div class="variant-label">Size</div><div class="size-options">${product.sizes?.map(s => `<button class="size-btn" onclick="this.closest('.size-options').querySelectorAll('.size-btn').forEach(b=>b.classList.remove('active'));this.classList.add('active');">${s}</button>`).join('')||''}</div></div>
    <div style="display:flex;gap:12px;margin-top:20px">
      <button class="add-to-cart-btn" style="flex:1" onclick="Cart.add({id:'${product.id}',name:'${product.name}',price:${product.price},image:'${product.images[0]}',variant:'Default'})">Add to Cart</button>
      <a href="${product.url}" class="btn btn-outline" style="white-space:nowrap">View Details</a>
    </div>`;
  modal.classList.add('active');
  document.getElementById('overlay')?.classList.add('active');
  document.body.style.overflow = 'hidden';
}
function closeQuickView() {
  document.getElementById('quickview-modal')?.classList.remove('active');
  document.getElementById('overlay')?.classList.remove('active');
  document.body.style.overflow = '';
}

// ===== NEWSLETTER =====
function initNewsletter() {
  document.querySelectorAll('.newsletter-form, .newsletter-form-large').forEach(form => {
    form.addEventListener('submit', (e) => {
      e.preventDefault();
      const input = form.querySelector('input[type="email"]');
      if (!input?.value) return;
      showToast('Thank you for subscribing!', 'success');
      input.value = '';
    });
  });
}

// ===== PRODUCTS DATA =====
const PRODUCTS_DATA = [
  // SHIRTS
  { id: 'men-light-gajari-color-fila-fill-soft-premium-cotton-formal-shirt-for-mens', name: "Men Light Gajari Color Fila Fill Soft Premium Cotton Formal Shirt For Mens", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08579.jpg'], url: '/shirts/men-light-gajari-color-fila-fill-soft-premium-cotton-formal-shirt-for-mens', category: 'shirts' },
  { id: 'men-mango-color-fila-fill-soft-premium-cotton-formal-shirt', name: "Men Mango Color Fila Fill Soft Premium Cotton Formal Shirt", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08956.jpg'], url: '/shirts/men-mango-color-fila-fill-soft-premium-cotton-formal-shirt', category: 'shirts' },
  { id: 'men-green-satin-finish-premium-cotton-shirt', name: "Men Green Satin Finish Premium Cotton Shirt", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08743.jpg'], url: '/shirts/men-green-satin-finish-premium-cotton-shirt', category: 'shirts' },
  { id: 'gray-color-oxford-soft-premium-cotton-formal-shirt-for-mens', name: "Gray Color Oxford Soft Premium Cotton Formal Shirt For Mens", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08664.jpg'], url: '/shirts/gray-color-oxford-soft-premium-cotton-formal-shirt-for-mens', category: 'shirts' },
  { id: 'men-maroon-dobby-premium-soft-cotton-shirt', name: "Men Maroon Dobby Premium Soft Cotton Shirt", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08921.jpg'], url: '/shirts/men-maroon-dobby-premium-soft-cotton-shirt', category: 'shirts' },
  { id: 'men-light-fawn-fila-fill-soft-premium-cotton-formal-shirt', name: "Men Light Fawn Fila Fill Soft Premium Cotton Formal Shirt", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08528.jpg'], url: '/shirts/men-light-fawn-fila-fill-soft-premium-cotton-formal-shirt', category: 'shirts' },
  { id: 'men-dark-grey-fila-fill-soft-premium-cotton-formal-shirt', name: "Men Dark Grey Fila Fill Soft Premium Cotton Formal Shirt", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08738.jpg'], url: '/shirts/men-dark-grey-fila-fill-soft-premium-cotton-formal-shirt', category: 'shirts' },
  { id: 'mens-white-satin-cotton-shirt', name: "Mens White Satin Cotton Shirt", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08673.jpg'], url: '/shirts/mens-white-satin-cotton-shirt', category: 'shirts' },
  { id: 'froze-color-fila-fill-soft-premium-cotton-formal-shirt-for-mens', name: "Froze Color Fila Fill Soft Premium Cotton Formal Shirt For Mens", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08628.jpg'], url: '/shirts/froze-color-fila-fill-soft-premium-cotton-formal-shirt-for-mens', category: 'shirts' },
  { id: 'men-light-gajari-color-oxford-soft-premium-cotton-formal-shirt-for-mens', name: "Men Light Gajari Color Oxford Soft Premium Cotton Formal Shirt For Mens", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08588.jpg'], url: '/shirts/men-light-gajari-color-oxford-soft-premium-cotton-formal-shirt-for-mens', category: 'shirts' },
  { id: 'men-green-color-oxford-soft-premium-cotton-formal-shirt-for-mens', name: "Men Green Color Oxford Soft Premium Cotton Formal Shirt For Mens", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08613.jpg'], url: '/shirts/men-green-color-oxford-soft-premium-cotton-formal-shirt-for-mens', category: 'shirts' },
  { id: 'men-light-broun-fila-fill-soft-premium-cotton-formal-shirt', name: "Men Light Broun Fila Fill Soft Premium Cotton Formal Shirt", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08796.jpg'], url: '/shirts/men-light-broun-fila-fill-soft-premium-cotton-formal-shirt', category: 'shirts' },
  { id: 'sky-color-fila-fill-soft-premium-cotton-formal-shirt-for-mens', name: "Sky Color Fila Fill Soft Premium Cotton Formal Shirt For Mens", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08543.jpg'], url: '/shirts/sky-color-fila-fill-soft-premium-cotton-formal-shirt-for-mens', category: 'shirts' },
  { id: 'men-lemon-color-super-soft-premium-dobby-cotton-formal-shirt', name: "Men Lemon Color Super Soft Premium Dobby Cotton Formal Shirt", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08473.jpg'], url: '/shirts/men-lemon-color-super-soft-premium-dobby-cotton-formal-shirt', category: 'shirts' },
  { id: 'men-dobby-royal-blue-premium-shirt', name: "Men Dobby Royal Blue Premium Shirt", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08974.jpg'], url: '/shirts/men-dobby-royal-blue-premium-shirt', category: 'shirts' },
  { id: 'men-pink-color-super-soft-premium-cotton-dobby-formal-shirt-for-mens', name: "Men Pink Color Super Soft Premium Cotton Dobby Formal Shirt For Mens", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08461.jpg'], url: '/shirts/men-pink-color-super-soft-premium-cotton-dobby-formal-shirt-for-mens', category: 'shirts' },
  { id: 'men-orange-color-super-soft-premium-cotton-dobby-formal-shirt', name: "Men Orange Color Super Soft Premium Cotton Dobby Formal Shirt", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08768.jpg'], url: '/shirts/men-orange-color-super-soft-premium-cotton-dobby-formal-shirt', category: 'shirts' },
  { id: 'men-purple-color-super-soft-premium-cotton-dobby-formal-shirt', name: "Men Purple Color Super Soft Premium Cotton Dobby Formal Shirt", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08836.jpg'], url: '/shirts/men-purple-color-super-soft-premium-cotton-dobby-formal-shirt', category: 'shirts' },
  { id: 'pista-green-color-fila-fill-soft-premium-cotton-formal-shirt', name: "Pista Green Color Fila Fill Soft Premium Cotton Formal Shirt", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08434.jpg'], url: '/shirts/pista-green-color-fila-fill-soft-premium-cotton-formal-shirt', category: 'shirts' },
  { id: 'men-black-super-soft-premium-cotton-satin-party-wear-shirt', name: "Men Black Super Soft Premium Cotton Satin Party Wear Shirt", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08903.jpg'], url: '/shirts/men-black-super-soft-premium-cotton-satin-party-wear-shirt', category: 'shirts' },
  { id: 'men-navy-blue-oxford-soft-premium-cotton-formal-shirt', name: "Men Navy Blue Oxford Soft Premium Cotton Formal Shirt", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08853.jpg'], url: '/shirts/men-navy-blue-oxford-soft-premium-cotton-formal-shirt', category: 'shirts' },
  { id: 'men-black-satin-finish-premium-cotton-shirt', name: "Men Black Satin Finish Premium Cotton Shirt", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08989.jpg'], url: '/shirts/men-black-satin-finish-premium-cotton-shirt', category: 'shirts' },
  { id: 'men-red-color-super-soft-premium-cotton-satin-party-wear-shirt', name: "Men Red Color Super Soft Premium Cotton Satin Party Wear Shirt", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08867.jpg'], url: '/shirts/men-red-color-super-soft-premium-cotton-satin-party-wear-shirt', category: 'shirts' },
  { id: 'men-fawn-color-super-soft-premium-cotton-dobby-formal-shirt-for-mens', name: "Men Fawn Color Super Soft Premium Cotton Dobby Formal Shirt For Mens", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08659.jpg'], url: '/shirts/men-fawn-color-super-soft-premium-cotton-dobby-formal-shirt-for-mens', category: 'shirts' },
  { id: 'men-mustard-color-super-soft-premium-cotton-dobby-formal-shirt-for-mens', name: "Men Mustard Color Super Soft Premium Cotton Dobby Formal Shirt For Mens", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08781.jpg'], url: '/shirts/men-mustard-color-super-soft-premium-cotton-dobby-formal-shirt-for-mens', category: 'shirts' },
  { id: 'men-orange-color-oxford-soft-premium-cotton-formal-shirt', name: "Men Orange Color Oxford Soft Premium Cotton Formal Shirt", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08644.jpg'], url: '/shirts/men-orange-color-oxford-soft-premium-cotton-formal-shirt', category: 'shirts' },
  { id: 'men-peach-color-super-soft-premium-cotton-dobby-formal-shirt-for-mens', name: "Men Peach Color Super Soft Premium Cotton Dobby Formal Shirt For Mens", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08558.jpg'], url: '/shirts/men-peach-color-super-soft-premium-cotton-dobby-formal-shirt-for-mens', category: 'shirts' },
  { id: 'men-sky-color-super-soft-premium-dobby-cotton-formal-shirt', name: "Men Sky Color Super Soft Premium Dobby Cotton Formal Shirt", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08500.jpg'], url: '/shirts/men-sky-color-super-soft-premium-dobby-cotton-formal-shirt', category: 'shirts' },
  { id: 'men-dark-pink-fila-fill-soft-premium-cotton-formal-shirt', name: "Men Dark Pink Fila Fill Soft Premium Cotton Formal Shirt", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08514.jpg'], url: '/shirts/men-dark-pink-fila-fill-soft-premium-cotton-formal-shirt', category: 'shirts' },
  { id: 'men-navy-blue-satin-finish-premium-cotton-shirt', name: "Men Navy Blue Satin Finish Premium Cotton Shirt", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08938.jpg'], url: '/shirts/men-navy-blue-satin-finish-premium-cotton-shirt', category: 'shirts' },
  { id: 'men-light-khaki-oxford-soft-premium-cotton-formal-shirt-for-mens', name: "Men Light Khaki Oxford Soft Premium Cotton Formal Shirt For Mens", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08708.jpg'], url: '/shirts/men-light-khaki-oxford-soft-premium-cotton-formal-shirt-for-mens', category: 'shirts' },
  { id: 'men-move-color-fila-fill-soft-premium-cotton-formal-shirt', name: "Men Move Color Fila Fill Soft Premium Cotton Formal Shirt", price: 1400, badge: 'Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08447.jpg'], url: '/shirts/men-move-color-fila-fill-soft-premium-cotton-formal-shirt', category: 'shirts' },
  // CHECK SHIRTS
  { id: 'p6888', name: "Men's Premium Firoz Printed Cotton Party Wear Shirt", price: 1400, badge: 'Check Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/02/New-Fabric__all_set255_hanger_shirt__2024-2-4-21-31-1__2730X4096.jpg'], url: '/shirts/check/men-premium-firoz-printed-cotton-party-wear-shirt', category: 'check-shirts' },
  { id: 'p6889', name: "Men's Premium Khaki Multi Color Printed Cotton Party Wear Shirt", price: 1400, badge: 'Check Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/02/New-Fabric__all_set255_hanger_shirt__2024-2-4-23-12-54__2730X4096.jpg'], url: '/shirts/check/mens-premium-khaki-multi-color-printed-cotton-party-wear-shirt', category: 'check-shirts' },
  { id: 'p6890', name: "Men's Premium Multi Color Printed Cotton Casual Party Wear Shirt", price: 1400, badge: 'Check Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/02/New-Fabric__all_set255_hanger_shirt__2024-2-5-20-23-13__2730X4096.jpg'], url: '/shirts/check/mens-premium-multi-color-printed-cotton-casual-party-wear-shirt', category: 'check-shirts' },
  { id: 'p6891', name: "Men's Premium Multi Color Printed Cotton Party Wear Shirt", price: 1400, badge: 'Check Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/02/New-Fabric__all_set255_hanger_shirt__2024-2-4-22-50-59__2730X4096.jpg'], url: '/shirts/check/mens-premium-multi-color-printed-cotton-party-wear-shirt', category: 'check-shirts' },
  { id: 'p6892', name: "Men's Premium Printed Cotton Party Wear Shirt", price: 1400, badge: 'Check Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/02/New-Fabric__all_set211_nomo_shirtfolded_front7__2024-2-4-21-56-17__2730X4096.jpg'], url: '/shirts/check/mens-premium-printed-cotton-party-wear-shirt', category: 'check-shirts' },
  { id: 'p6893', name: "Men's Premium Sky Color Printed Cotton Regular Fit Shirt", price: 1400, badge: 'Check Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/02/New-Fabric__all_set255_hanger_shirt__2024-2-4-21-8-40__2730X4096.jpg'], url: '/shirts/check/mens-premium-sky-color-printed-cotton-regular-fit-shirt', category: 'check-shirts' },
  // STRAP SHIRTS
  { id: 'p9462', name: "Men's Premium Stripe Cotton Formal Shirt", price: 1400, badge: 'Strap Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/02/lining-shirt-__ocm_b3_acrylicshirt_4__2024-2-4-20-5-35__2730X4096.jpg'], url: '/shirts/strap/mens-stripe-cotton-formal-shirt', category: 'strap-shirts' },
  { id: 'p9482', name: "Men's Light Blue With White Stripe Cotton Formal Shirt", price: 1400, badge: 'Strap Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/02/shirt-__ocm_b3_acrylicshirt_4__2024-2-4-20-33-28__2730X4096.jpg'], url: '/shirts/strap/mens-light-blue-with-white-stripe-cotton-formal-shirt', category: 'strap-shirts' },
  { id: 'p9503', name: "Men's Premium Multi Color Stripe Cotton Formal Shirt", price: 1400, badge: 'Strap Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/02/shirt-__ocm_b3_acrylicshirt_4__2024-2-4-20-52-50__2730X4096.jpg'], url: '/shirts/strap/mens-premium-muliti-color-stripe-cotton-formal-shirt', category: 'strap-shirts' },
  // TROUSERS
  { id: 'mens-grey-check-italian-formal-trouser', name: "Mens Grey Check Italian Formal Trouser", price: 3000, badge: 'Trousers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/Raymond-wool-grey__a4_all_set158_trouser_front__2024-1-31-17-11-0__2730X4096.jpg'], url: '/trousers/mens-grey-check-italian-formal-trouser', category: 'trousers' },
  { id: 'mens-regular-fit-lycra-jeans', name: "Mens Regular Fit Lycra Jeans", price: 3000, badge: 'Trousers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/t-wool-col-40__a4_all_set158_trouser_front__2024-1-31-19-11-15__2730X4096.jpg'], url: '/trousers/mens-regular-fit-lycra-jeans', category: 'trousers' },
  { id: 'mens-blue-italian-regular-trouser', name: "Mens Blue Italian Regular Trouser", price: 3000, badge: 'Trousers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/t-wool-col-19__a4_all_set158_trouser_front__2024-1-31-22-59-54__2730X4096.jpg'], url: '/trousers/mens-blue-italian-regular-trouser', category: 'trousers' },
  { id: 'mens-light-green-check-trouser', name: "Mens Light Green Check Trouser", price: 3000, badge: 'Trousers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/Khaki__a4_all_set158_trouser_front__2024-1-31-16-57-50__2730X4096.jpg'], url: '/trousers/mens-light-green-check-trouser', category: 'trousers' },
  { id: 'mens-grey-lycra-jeans', name: "Mens Grey Lycra Jeans", price: 3000, badge: 'Trousers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS09236.jpg'], url: '/trousers/mens-grey-lycra-jeans', category: 'trousers' },
  { id: 'mens-grey-regular-trouser', name: "Mens Grey Regular Trouser", price: 3000, badge: 'Trousers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/New-Fabric__a4_all_set158_trouser_back__2024-1-31-16-42-52__2730X4096.jpg'], url: '/trousers/mens-grey-regular-trouser', category: 'trousers' },
  { id: 'crpf-cotton-combat-trouser-for-pt', name: "Crpf Cotton Combat Trouser For Pt", price: 3000, badge: 'Trousers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/Best-wardi-shop-for-army-police.png'], url: '/trousers/crpf-cotton-combat-trouser-for-pt', category: 'trousers' },
  { id: 'mens-light-grey-italian-wool-trouser', name: "Mens Light Grey Italian Wool Trouser", price: 3000, badge: 'Trousers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/t-wool-col-19__a4_all_set158_trouser_front__2024-1-31-22-59-54__2730X4096.jpg'], url: '/trousers/mens-light-grey-italian-wool-trouser', category: 'trousers' },
  { id: 'mens-grey-stripe-italian-trouser', name: "Mens Grey Stripe Italian Trouser", price: 3000, badge: 'Trousers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/t-wool-col-28__fab_swatch_square__2024-1-31-22-40-51__2730X4096.jpg'], url: '/trousers/mens-grey-stripe-italian-trouser', category: 'trousers' },
  { id: 'mens-light-parrot-green-formal-trouser', name: "Mens Light Parrot Green Formal Trouser", price: 3000, badge: 'Trousers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/t-wool-col-36__a4_all_set158_trouser_back__2024-1-31-19-2-34__2730X4096.jpg'], url: '/trousers/mens-light-parrot-green-formal-trouser', category: 'trousers' },
  { id: 'crpf-cotton-combat-trouser-for-pt-2', name: "Crpf Cotton Combat Trouser For Pt 2", price: 3000, badge: 'Trousers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00600-copy.jpg'], url: '/trousers/crpf-cotton-combat-trouser-for-pt-2', category: 'trousers' },
  { id: 'mens-light-blue-italian-trouser', name: "Mens Light Blue Italian Trouser", price: 3000, badge: 'Trousers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/T-wool-Col-38__a4_all_set158_trouser_back__2024-1-31-19-5-22__2730X4096.jpg'], url: '/trousers/mens-light-blue-italian-trouser', category: 'trousers' },
  { id: 'mens-khaki-formal-trouser', name: "Mens Khaki Formal Trouser", price: 3000, badge: 'Trousers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/Khaki__a4_all_set158_trouser_back__2024-1-31-16-58-6__2730X4096.jpg'], url: '/trousers/mens-khaki-formal-trouser', category: 'trousers' },
  { id: 'mens-light-green-formal-trouser', name: "Mens Light Green Formal Trouser", price: 3000, badge: 'Trousers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/t-wool-color-03__a4_all_set158_trouser_back__2024-1-31-17-15-0__2730X4096.jpg'], url: '/trousers/mens-light-green-formal-trouser', category: 'trousers' },
  { id: 'mens-blue-italian-terry-wool-trouser', name: "Mens Blue Italian Terry Wool Trouser", price: 3000, badge: 'Trousers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/t-wool-col-39__a4_all_set158_trouser_back__2024-1-31-19-9-36__2730X4096.jpg'], url: '/trousers/mens-blue-italian-terry-wool-trouser', category: 'trousers' },
  { id: 'mens-dark-blue-italian-formal-trouser', name: "Mens Dark Blue Italian Formal Trouser", price: 3000, badge: 'Trousers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/T-wool-col-32__a4_all_set158_trouser_back__2024-1-31-22-48-4__2730X4096.jpg'], url: '/trousers/mens-dark-blue-italian-formal-trouser', category: 'trousers' },
  // BLAZERS
  { id: 'men-ink-blue-regular-fit-blazer', name: "Men Ink Blue Regular Fit Blazer", price: 3000, badge: 'Blazers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/01/1000040080.jpg'], url: '/blazers/men-ink-blue-regular-fit-blazer', category: 'blazers' },
  { id: 'mens-light-parrot-green-regular-fit-blazer', name: "Mens Light Parrot Green Regular Fit Blazer", price: 3000, badge: 'Blazers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/01/1000040273.jpg'], url: '/blazers/mens-light-parrot-green-regular-fit-blazer', category: 'blazers' },
  { id: 'men-royal-green-color-regular-fit-blazer', name: "Men Royal Green Color Regular Fit Blazer", price: 3000, badge: 'Blazers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/01/1000040303.jpg'], url: '/blazers/men-royal-green-color-regular-fit-blazer', category: 'blazers' },
  { id: 'men-khaki-color-terry-rayon-regular-fit-blazer', name: "Men Khaki Color Terry Rayon Regular Fit Blazer", price: 3000, badge: 'Blazers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/01/1000040273.jpg'], url: '/blazers/men-khaki-color-terry-rayon-regular-fit-blazer', category: 'blazers' },
  { id: 'men-grey-color-terry-rayon-regular-fit-blazer', name: "Men Grey Color Terry Rayon Regular Fit Blazer", price: 3000, badge: 'Blazers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/01/1000040299.jpg'], url: '/blazers/men-grey-color-terry-rayon-regular-fit-blazer', category: 'blazers' },
  { id: 'men-black-terry-rayon-regular-fit-blazer', name: "Men Black Terry Rayon Regular Fit Blazer", price: 3000, badge: 'Blazers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/01/1000040091.jpg'], url: '/blazers/men-black-terry-rayon-regular-fit-blazer', category: 'blazers' },
  { id: 'men-dark-brick-color-regular-fit-blazer', name: "Men Dark Brick Color Regular Fit Blazer", price: 3000, badge: 'Blazers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/01/1000040256.jpg'], url: '/blazers/men-dark-brick-color-regular-fit-blazer', category: 'blazers' },
  { id: 'men-light-grey-check-regular-fit-blazer', name: "Men Light Grey Check Regular Fit Blazer", price: 3000, badge: 'Blazers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/01/1000040106.jpg'], url: '/blazers/men-light-grey-check-regular-fit-blazer', category: 'blazers' },
  { id: 'men-brown-color-terry-rayon-regular-fit-blazer', name: "Men Brown Color Terry Rayon Regular Fit Blazer", price: 3000, badge: 'Blazers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/01/1000040269.jpg'], url: '/blazers/men-brown-color-terry-rayon-regular-fit-blazer', category: 'blazers' },
  { id: 'men-blue-stripe-terry-rayon-regular-fit-blazer', name: "Men Blue Stripe Terry Rayon Regular Fit Blazer", price: 3000, badge: 'Blazers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/01/1000040076.jpg'], url: '/blazers/men-blue-stripe-terry-rayon-regular-fit-blazer', category: 'blazers' },
  { id: 'men-sky-color-regular-fit-blazer', name: "Men Sky Color Regular Fit Blazer", price: 3000, badge: 'Blazers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/01/1000040275.jpg'], url: '/blazers/men-sky-color-regular-fit-blazer', category: 'blazers' },
  { id: 'men-dark-grey-blazer-italian-terry-rayon', name: "Men Dark Grey Blazer Italian Terry Rayon", price: 3000, badge: 'Blazers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/01/1000040138.jpg'], url: '/blazers/men-dark-grey-blazer-italian-terry-rayon', category: 'blazers' },
  { id: 'maroon-check-terry-wool-blazer', name: "Maroon Check Terry Wool Blazer", price: 3000, badge: 'Blazers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/01/1000040131.jpg'], url: '/blazers/maroon-check-terry-wool-blazer', category: 'blazers' },
  { id: 'men-navy-blue-formal-blazer', name: "Men Navy Blue Formal Blazer", price: 3000, badge: 'Blazers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/01/1000040101.jpg'], url: '/blazers/men-navy-blue-formal-blazer', category: 'blazers' },
  { id: 'men-grey-terry-wool-stripe-formal-blazer', name: "Men Grey Terry Wool Stripe Formal Blazer", price: 3000, badge: 'Blazers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/01/1000040142.jpg'], url: '/blazers/men-grey-terry-wool-stripe-formal-blazer', category: 'blazers' },
  { id: 'men-light-blue-check-regular-fit-blazer', name: "Men Light Blue Check Regular Fit Blazer", price: 3000, badge: 'Blazers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/01/1000040127.jpg'], url: '/blazers/men-light-blue-check-regular-fit-blazer', category: 'blazers' },
  { id: 'men-navy-blue-woven-italian-classic-blazer', name: "Men Navy Blue Woven Italian Classic Blazer", price: 3000, badge: 'Blazers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/01/1000040293.jpg'], url: '/blazers/men-navy-blue-woven-italian-classic-blazer', category: 'blazers' },
  { id: 'men-light-green-formal-fit-blazer', name: "Men Light Green Formal Fit Blazer", price: 3000, badge: 'Blazers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/01/1000040097.jpg'], url: '/blazers/men-light-green-formal-fit-blazer', category: 'blazers' },
  { id: 'men-light-grey-check-formal-fit-blazer', name: "Men Light Grey Check Formal Fit Blazer", price: 3000, badge: 'Blazers', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/01/1000040087.jpg'], url: '/blazers/men-light-grey-check-formal-fit-blazer', category: 'blazers' },
  // MODI JACKET
  { id: 'men-light-yellow-jacquard-modi-jacket-with-silk-kurta-pajama', name: "Men Light Yellow Jacquard Modi Jacket With Silk Kurta Pajama", price: 3000, badge: 'Modi Jacket', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/02/t-wool-col-36__all_set309_nehrujacket_side__2024-2-10-20-56-34__2730X4096.jpg'], url: '/modi-jacket/men-light-yellow-jacquard-modi-jacket-with-silk-kurta-pajama', category: 'modi-jacket' },
  { id: 'men-yellow-jacquard-jacket-with-silk-kurta-and-pajama', name: "Men Yellow Jacquard Jacket With Silk Kurta And Pajama", price: 3000, badge: 'Modi Jacket', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/02/t-wool-col-40__all_set309_nehrujacket_side__2024-2-10-20-52-8__2730X4096.jpg'], url: '/modi-jacket/men-yellow-jacquard-jacket-with-silk-kurta-and-pajama', category: 'modi-jacket' },
  { id: 'mens-blue-check-with-wool-rich-modi-jacket', name: "Mens Blue Check With Wool Rich Modi Jacket", price: 3000, badge: 'Modi Jacket', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/02/t-wool-col-36__all_set309_nehrujacket_side__2024-2-10-20-56-34__2730X4096.jpg'], url: '/modi-jacket/mens-blue-check-with-wool-rich-modi-jacket', category: 'modi-jacket' },
  { id: 'mens-dark-blue-color-check-with-wool-rich-modi-jacket', name: "Mens Dark Blue Color Check With Wool Rich Modi Jacket", price: 3000, badge: 'Modi Jacket', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/02/t-wool-col-33__all_set309_nehrujacket_side__2024-2-10-20-59-7__2730X4096.jpg'], url: '/modi-jacket/mens-dark-blue-color-check-with-wool-rich-modi-jacket', category: 'modi-jacket' },
  { id: 'mens-gray-check-modi-jacket', name: "Mens Gray Check Modi Jacket", price: 3000, badge: 'Modi Jacket', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/02/t-wool-col-40__all_set309_nehrujacket_side__2024-2-10-20-52-8__2730X4096.jpg'], url: '/modi-jacket/mens-gray-check-modi-jacket', category: 'modi-jacket' },
  { id: 'mens-ink-blue-check-with-wool-rich-modi-jacket', name: "Mens Ink Blue Check With Wool Rich Modi Jacket", price: 3000, badge: 'Modi Jacket', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/02/t-wool-col-36__all_set309_nehrujacket_side__2024-2-10-20-56-34__2730X4096.jpg'], url: '/modi-jacket/mens-ink-blue-check-with-wool-rich-modi-jacket', category: 'modi-jacket' },
  { id: 'mens-light-parrot-green-check-with-wool-rich-modi-jacket', name: "Mens Light Parrot Green Check With Wool Rich Modi Jacket", price: 3000, badge: 'Modi Jacket', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/02/t-wool-col-36__all_set309_nehrujacket_side__2024-2-10-20-56-34__2730X4096.jpg'], url: '/modi-jacket/mens-light-parrot-green-check-with-wool-rich-modi-jacket', category: 'modi-jacket' },
  { id: 'mens-navy-blue-modi-jacket', name: "Mens Navy Blue Modi Jacket", price: 3000, badge: 'Modi Jacket', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/02/terry-rayon-52a__all_set309_nehrujacket_front0__2024-2-10-20-50-20__2730X4096.jpg'], url: '/modi-jacket/mens-navy-blue-modi-jacket', category: 'modi-jacket' },
  { id: 'mens-wine-color-check-with-wool-rich-modi-jacket', name: "Mens Wine Color Check With Wool Rich Modi Jacket", price: 3000, badge: 'Modi Jacket', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/02/t-wool-col-33__all_set309_nehrujacket_side__2024-2-10-20-59-7__2730X4096.jpg'], url: '/modi-jacket/mens-wine-color-check-with-wool-rich-modi-jacket', category: 'modi-jacket' },
  // SUITS
  { id: 'mens-blue-color-classic-luxurious-3-piece-suits', name: "Mens Blue Color Classic Luxurious 3 Piece Suits", price: 3000, badge: 'Suits', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/02/Tri3dImage_1705511971791.jpeg'], url: '/suits/mens-blue-color-classic-luxurious-3-piece-suits', category: 'suits' },
  { id: 'mens-light-blue-check-italian-terry-wool-classic-luxurious-3-piece-suits', name: "Mens Light Blue Check Italian Terry Wool Classic Luxurious 3 Piece Suits", price: 3000, badge: 'Suits', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/02/Tri3dImage_1705512877113.jpeg'], url: '/suits/mens-light-blue-check-italian-terry-wool-classic-luxurious-3-piece-suits', category: 'suits' },
  { id: 'men-dark-blue-sequins-embroidered-tuxedo-blazer-with-blue-vest-coat-and-pant', name: "Men Dark Blue Sequins Embroidered Tuxedo Blazer With Blue Vest Coat And Pant", price: 3000, badge: 'Suits', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08363.jpg'], url: '/suits/men-dark-blue-sequins-embroidered-tuxedo-blazer-with-blue-vest-coat-and-pant', category: 'suits' },
  { id: 'men-grey-tuxedo-3-piece-suits-wedding-groomsmen-fashion-suits', name: "Men Grey Tuxedo 3 Piece Suits Wedding Groomsmen Fashion Suits", price: 3000, badge: 'Suits', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08341.jpg'], url: '/suits/men-grey-tuxedo-3-piece-suits-wedding-groomsmen-fashion-suits', category: 'suits' },
  { id: 'men-blue-classic-formal-2-piece-suit', name: "Men Blue Classic Formal 2 Piece Suit", price: 3000, badge: 'Suits', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/Tri3dImage_1706373623330.jpeg'], url: '/suits/men-blue-classic-formal-2-piece-suit', category: 'suits' },
  { id: 'mens-grey-classic-luxurious-3-piece-suits', name: "Mens Grey Classic Luxurious 3 Piece Suits", price: 3000, badge: 'Suits', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/02/Tri3dImage_1705512411584.jpeg'], url: '/suits/mens-grey-classic-luxurious-3-piece-suits', category: 'suits' },
  { id: 'men-black-sequins-embroidered-tuxedo-3-piece-suit', name: "Men Black Sequins Embroidered Tuxedo 3 Piece Suit", price: 3000, badge: 'Suits', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08407.jpg'], url: '/suits/men-black-sequins-embroidered-tuxedo-3-piece-suit', category: 'suits' },
  { id: 'men-grey-formal-fashion-suit', name: "Men Grey Formal Fashion Suit", price: 3000, badge: 'Suits', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/Tri3dImage_1706374290487.jpeg'], url: '/suits/men-grey-formal-fashion-suit', category: 'suits' },
  { id: 'mens-wine-color-check-italian-terry-wool-classic-luxurious-3-piece-suit', name: "Mens Wine Color Check Italian Terry Wool Classic Luxurious 3 Piece Suit", price: 3000, badge: 'Suits', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/02/Tri3dImage_1705513366514.jpeg'], url: '/suits/mens-wine-color-check-italian-terry-wool-classic-luxurious-3-piece-suit', category: 'suits' },
  { id: 'men-khaki-classic-luxurious-men-suits', name: "Men Khaki Classic Luxurious Men Suits", price: 3000, badge: 'Suits', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/Tri3dImage_1706373724108.jpeg'], url: '/suits/men-khaki-classic-luxurious-men-suits', category: 'suits' },
  { id: 'men-maroon-sequins-embroidered-tuxedo-3-piece-suit', name: "Men Maroon Sequins Embroidered Tuxedo 3 Piece Suit", price: 3000, badge: 'Suits', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2023/12/CKS08393.jpg'], url: '/suits/men-maroon-sequins-embroidered-tuxedo-3-piece-suit', category: 'suits' },
  { id: 'mens-parrot-color-classic-luxurious-3-piece-suit', name: "Mens Parrot Color Classic Luxurious 3 Piece Suit", price: 3000, badge: 'Suits', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/02/Tri3dImage_17055051776591.jpeg'], url: '/suits/mens-parrot-color-classic-luxurious-3-piece-suit', category: 'suits' },
  { id: 'mens-light-parrot-green-check-italian-terry-wool-classic-luxurious-3-piece-suit', name: "Mens Light Parrot Green Check Italian Terry Wool Classic Luxurious 3 Piece Suit", price: 3000, badge: 'Suits', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/02/Tri3dImage_1705513041052.jpeg'], url: '/suits/mens-light-parrot-green-check-italian-terry-wool-classic-luxurious-3-piece-suit', category: 'suits' },
  // UNIFORMS
  { id: 'khaki-uniform-vimal-prmium-super-trovine', name: "Khaki Uniform Vimal Prmium Super Trovine", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00555.jpg'], url: '/uniforms/khaki-uniform-vimal-prmium-super-trovine', category: 'uniforms' },
  { id: 'khaki-uniform-siyaram-matty', name: "Khaki Uniform Siyaram Matty", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00565.jpg'], url: '/uniforms/khaki-uniform-siyaram-matty', category: 'uniforms' },
  { id: 'khaki-uniform-vimal-prmium', name: "Khaki Uniform Vimal Prmium", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00631-copy.jpg'], url: '/uniforms/khaki-uniform-vimal-prmium', category: 'uniforms' },
  { id: 'khaki-uniform-vimal-prmium-trovine', name: "Khaki Uniform Vimal Prmium Trovine", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00641-copy.jpg'], url: '/uniforms/khaki-uniform-vimal-prmium-trovine', category: 'uniforms' },
  { id: 'khaki-uniform-vimal-sapphre', name: "Khaki Uniform Vimal Sapphre", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00544.jpg'], url: '/uniforms/khaki-uniform-vimal-sapphre', category: 'uniforms' },
  { id: 'khaki-uniform-vimal-super-trovine', name: "Khaki Uniform Vimal Super Trovine", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00668-copy.jpg'], url: '/uniforms/khaki-uniform-vimal-super-trovine', category: 'uniforms' },
  { id: 'khaki-uniform-oswal-ajanta-super-primium-trovin', name: "Khaki Uniform Oswal Ajanta Super Primium Trovin", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00575-copy.jpg'], url: '/uniforms/khaki-uniform-oswal-ajanta-super-primium-trovin', category: 'uniforms' },
  { id: 'khaki-uniform-vimal-super-trovine-2', name: "Khaki Uniform Vimal Super Trovine 2", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00682-copy.jpg'], url: '/uniforms/khaki-uniform-vimal-super-trovine-2', category: 'uniforms' },
  { id: 'khaki-uniform-vimal-officer-strech-fit', name: "Khaki Uniform Vimal Officer Strech Fit", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00693.jpg'], url: '/uniforms/khaki-uniform-vimal-officer-strech-fit', category: 'uniforms' },
  { id: 'khki-uniform-vimal-primium-trovin', name: "Khki Uniform Vimal Primium Trovin", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00653-copy.jpg'], url: '/uniforms/khki-uniform-vimal-primium-trovin', category: 'uniforms' },
  { id: 'khaki-uniform-vimal-officer-strech-fit-27', name: "Khaki Uniform Vimal Officer Strech Fit 27", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00472-1.jpg'], url: '/uniforms/khaki-uniform-vimal-officer-strech-fit-27', category: 'uniforms' },
  { id: 'khaki-uniform-vimal-super-trovine-3', name: "Khaki Uniform Vimal Super Trovine 3", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00682-copy.jpg'], url: '/uniforms/khaki-uniform-vimal-super-trovine-3', category: 'uniforms' },
  { id: 'ssb-khaki-uniform-vimal-super-trovine-2', name: "Ssb Khaki Uniform Vimal Super Trovine 2", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00631-copy.jpg'], url: '/uniforms/ssb/ssb-khaki-uniform-vimal-super-trovine-2', category: 'uniforms' },
  { id: 'ssb-khaki-uniform-by-vimal-primium-trovine', name: "Ssb Khaki Uniform By Vimal Primium Trovine", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00653-copy.jpg'], url: '/uniforms/ssb/ssb-khaki-uniform-by-vimal-primium-trovine', category: 'uniforms' },
  { id: 'ssb-khaki-uniform-by-vimal-sapphire', name: "Ssb Khaki Uniform By Vimal Sapphire", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00554.jpg'], url: '/uniforms/ssb/ssb-khaki-uniform-by-vimal-sapphire', category: 'uniforms' },
  { id: 'ssb-khaki-uniform-vimal-prmium-trovine-light-color', name: "Ssb Khaki Uniform Vimal Prmium Trovine Light Color", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00641-copy.jpg'], url: '/uniforms/ssb/ssb-khaki-uniform-vimal-prmium-trovine-light-color', category: 'uniforms' },
  { id: 'ssb-stretchable-khaki-uniform-by-vimal-officer-stretch-fit', name: "Ssb Stretchable Khaki Uniform By Vimal Officer Stretch Fit", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00693.jpg'], url: '/uniforms/ssb/ssb-stretchable-khaki-uniform-by-vimal-officer-stretch-fit', category: 'uniforms' },
  { id: 'ssb-khaki-uniform-by-vimal-super-trovine-2', name: "Ssb Khaki Uniform By Vimal Super Trovine 2", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00668-copy.jpg'], url: '/uniforms/ssb/ssb-khaki-uniform-by-vimal-super-trovine-2', category: 'uniforms' },
  { id: 'ssb-khaki-uniform-vimal-super-trovine', name: "Ssb Khaki Uniform Vimal Super Trovine", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00682-copy.jpg'], url: '/uniforms/ssb/ssb-khaki-uniform-vimal-super-trovine', category: 'uniforms' },
  { id: 'ssb-khaki-uniform-by-siyaram-matte', name: "Ssb Khaki Uniform By Siyaram Matte", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00565.jpg'], url: '/uniforms/ssb/ssb-khaki-uniform-by-siyaram-matte', category: 'uniforms' },
  { id: 'ssb-khaki-uniform-by-vimal-super-trovine', name: "Ssb Khaki Uniform By Vimal Super Trovine", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00682-copy.jpg'], url: '/uniforms/ssb/ssb-khaki-uniform-by-vimal-super-trovine', category: 'uniforms' },
  { id: 'https-treyondworld-com-crpf-combat-uniform-tactical-belt', name: "Https Treyondworld Com Crpf Combat Uniform Tactical Belt", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/06/CKS02486-copy.jpg'], url: '/uniforms/combat/https-treyondworld-com-crpf-combat-uniform-tactical-belt', category: 'uniforms' },
  { id: 'https-treyondworld-com-beret-cap-for-bsf', name: "Https Treyondworld Com Beret Cap For Bsf", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/06/CKS02468-copy.jpg'], url: '/uniforms/combat/https-treyondworld-com-beret-cap-for-bsf', category: 'uniforms' },
  { id: 'crpf-combat-uniform-cool-touch-fast-color-by-ajanta-for-head-constable', name: "Crpf Combat Uniform Cool Touch Fast Color By Ajanta For Head Constable", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00590-copy.jpg'], url: '/uniforms/combat/crpf-combat-uniform-cool-touch-fast-color-by-ajanta-for-head-constable', category: 'uniforms' },
  { id: 'crpf-combat-uniform-pakka-color-for-sub-insptor', name: "Crpf Combat Uniform Pakka Color For Sub Insptor", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00590-copy.jpg'], url: '/uniforms/combat/crpf-combat-uniform-pakka-color-for-sub-insptor', category: 'uniforms' },
  { id: 'crpf-cotton-80-20-us-pattern-combat', name: "Crpf Cotton 80 20 Us Pattern Combat", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00600-copy.jpg'], url: '/uniforms/combat/crpf-cotton-80-20-us-pattern-combat', category: 'uniforms' },
  { id: 'https-treyondworld-com-leather-boot-for-paramilitary', name: "Https Treyondworld Com Leather Boot For Paramilitary", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/06/CKS02525-copy.jpg'], url: '/uniforms/combat/https-treyondworld-com-leather-boot-for-paramilitary', category: 'uniforms' },
  { id: 'crpf-combat-cotton-80-poly-20-us-pattern-wardi', name: "Crpf Combat Cotton 80 Poly 20 Us Pattern Wardi", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00598-copy-scaled.jpg'], url: '/uniforms/combat/crpf-combat-cotton-80-poly-20-us-pattern-wardi', category: 'uniforms' },
  { id: 'crpf-combat-uniform-pakka-color-for-constable', name: "Crpf Combat Uniform Pakka Color For Constable", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00590-copy.jpg'], url: '/uniforms/combat/crpf-combat-uniform-pakka-color-for-constable', category: 'uniforms' },
  { id: 'ssb-new-pattern-combat-uniform', name: "Ssb New Pattern Combat Uniform", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00772.jpg'], url: '/uniforms/combat/ssb-new-pattern-combat-uniform', category: 'uniforms' },
  { id: 'https-treyondworld-com-bsf-combat-uniform-tactical-belt', name: "Https Treyondworld Com Bsf Combat Uniform Tactical Belt", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/06/CKS02492-copy.jpg'], url: '/uniforms/combat/https-treyondworld-com-bsf-combat-uniform-tactical-belt', category: 'uniforms' },
  { id: 'https-treyondworld-com-blue-beret-cap-crp-ssb', name: "Https Treyondworld Com Blue Beret Cap Crp Ssb", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/06/CKS02461-copy.jpg'], url: '/uniforms/combat/https-treyondworld-com-blue-beret-cap-crp-ssb', category: 'uniforms' },
  { id: 'combet-uniform-manipuri-pattern-cool-touch', name: "Combet Uniform Manipuri Pattern Cool Touch", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00615-copy.jpg'], url: '/uniforms/combat/combet-uniform-manipuri-pattern-cool-touch', category: 'uniforms' },
  { id: 'https-treyondworld-com-d-m-boot-for-bsf-crpf-ssb-itbp', name: "Https Treyondworld Com D M Boot For Bsf Crpf Ssb Itbp", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/06/CKS02504-copy-1.jpg'], url: '/uniforms/combat/https-treyondworld-com-d-m-boot-for-bsf-crpf-ssb-itbp', category: 'uniforms' },
  { id: 'crpf-combat-uniform-cool-touch-fast-colour-by-ajanta', name: "Crpf Combat Uniform Cool Touch Fast Colour By Ajanta", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/crpf-poly-coot-touch-main-photo.jpg'], url: '/uniforms/combat/crpf-combat-uniform-cool-touch-fast-colour-by-ajanta', category: 'uniforms' },
  { id: 'crpf-cotton-us-pattern-combat-uniform', name: "Crpf Cotton Us Pattern Combat Uniform", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00598-copy-scaled.jpg'], url: '/uniforms/combat/crpf-cotton-us-pattern-combat-uniform', category: 'uniforms' },
  { id: 'crpf-combat-uniform-pakka-color-for-asi', name: "Crpf Combat Uniform Pakka Color For Asi", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00590-copy.jpg'], url: '/uniforms/combat/crpf-combat-uniform-pakka-color-for-asi', category: 'uniforms' },
  { id: 'crpf-combat-mix-pakka-color-wardi', name: "Crpf Combat Mix Pakka Color Wardi", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00590-copy.jpg'], url: '/uniforms/combat/crpf-combat-mix-pakka-color-wardi', category: 'uniforms' },
  { id: 'https-treyondworld-com-crpf-monkey-caf', name: "Https Treyondworld Com Crpf Monkey Caf", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/06/CKS02478-copy.jpg'], url: '/uniforms/combat/https-treyondworld-com-crpf-monkey-caf', category: 'uniforms' },
  { id: 'ssb-new-pattern-combat', name: "Ssb New Pattern Combat", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00743-scaled.jpg'], url: '/uniforms/combat/ssb-new-pattern-combat', category: 'uniforms' },
  { id: 'crpf-combet-manipuri-pattern-uniform-cool-touch', name: "Crpf Combet Manipuri Pattern Uniform Cool Touch", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00613-copy-scaled.jpg'], url: '/uniforms/combat/crpf-combet-manipuri-pattern-uniform-cool-touch', category: 'uniforms' },
  { id: 'https-treyondworld-com-dm-boot-crpf-ssb-itbp-bsf-cisf', name: "Https Treyondworld Com Dm Boot Crpf Ssb Itbp Bsf Cisf", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/06/CKS02499-copy.jpg'], url: '/uniforms/combat/https-treyondworld-com-dm-boot-crpf-ssb-itbp-bsf-cisf', category: 'uniforms' },
  { id: 'combat-us-pattern-ssb-uniform', name: "Combat Us Pattern Ssb Uniform", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00729.jpg'], url: '/uniforms/combat/combat-us-pattern-ssb-uniform', category: 'uniforms' },
  { id: 'us-pattern-combet-uniform-officer-choice-by-valiant-vimal', name: "Us Pattern Combet Uniform Officer Choice By Valiant Vimal", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00600-copy.jpg'], url: '/uniforms/combat/us-pattern-combet-uniform-officer-choice-by-valiant-vimal', category: 'uniforms' },
  { id: 'ssb-new-pattern-combat-uniforms', name: "Ssb New Pattern Combat Uniforms", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00770-scaled.jpg'], url: '/uniforms/combat/ssb-new-pattern-combat-uniforms', category: 'uniforms' },
  { id: 'crpf-cotton-combat-uniform-constable', name: "Crpf Cotton Combat Uniform Constable", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00600-copy.jpg'], url: '/uniforms/combat/crpf-cotton-combat-uniform-constable', category: 'uniforms' },
  { id: 'crpf-combat-uniform-pakka-color-for-constable-2', name: "Crpf Combat Uniform Pakka Color For Constable 2", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00590-copy.jpg'], url: '/uniforms/combat/crpf-combat-uniform-pakka-color-for-constable-2', category: 'uniforms' },
  { id: 'combat-uniform-cool-touch-fast-colour-by-ajanta', name: "Combat Uniform Cool Touch Fast Colour By Ajanta", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00590-copy.jpg'], url: '/uniforms/combat/combat-uniform-cool-touch-fast-colour-by-ajanta', category: 'uniforms' },
  { id: 'https-treyondworld-com-jungle-boot-for-peramilitary', name: "Https Treyondworld Com Jungle Boot For Peramilitary", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/06/CKS02536-copy.jpg'], url: '/uniforms/combat/https-treyondworld-com-jungle-boot-for-peramilitary', category: 'uniforms' },
  { id: 'crpf-combat-uniform-pakka-color-for-head-constable', name: "Crpf Combat Uniform Pakka Color For Head Constable", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00590-copy.jpg'], url: '/uniforms/combat/crpf-combat-uniform-pakka-color-for-head-constable', category: 'uniforms' },
  { id: 'crpf-cotton-combat-uniform', name: "Crpf Cotton Combat Uniform", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00600-copy.jpg'], url: '/uniforms/combat/crpf-cotton-combat-uniform', category: 'uniforms' },
  { id: 'crpf-combat-uniform-cool-touch-pakka-color-for-asi', name: "Crpf Combat Uniform Cool Touch Pakka Color For Asi", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00590-copy.jpg'], url: '/uniforms/combat/crpf-combat-uniform-cool-touch-pakka-color-for-asi', category: 'uniforms' },
  { id: 'crpf-cotton-combat-uniform-for-asi', name: "Crpf Cotton Combat Uniform For Asi", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00600-copy.jpg'], url: '/uniforms/combat/crpf-cotton-combat-uniform-for-asi', category: 'uniforms' },
  { id: 'crpf-combat-uniform', name: "Crpf Combat Uniform", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00600-copy.jpg'], url: '/uniforms/combat/crpf-combat-uniform', category: 'uniforms' },
  { id: 'crpf-combat-uniform-cool-touch-pakka-color-for-sub-insptor', name: "Crpf Combat Uniform Cool Touch Pakka Color For Sub Insptor", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00590-copy.jpg'], url: '/uniforms/combat/crpf-combat-uniform-cool-touch-pakka-color-for-sub-insptor', category: 'uniforms' },
  { id: 'ssb-us-pattern-combat-uniform-ssb-3', name: "Ssb Us Pattern Combat Uniform Ssb 3", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00758-scaled.jpg'], url: '/uniforms/combat/ssb-us-pattern-combat-uniform-ssb-3', category: 'uniforms' },
  { id: 'crpf-cotton-combat-uniform-for-sub-inspector', name: "Crpf Cotton Combat Uniform For Sub Inspector", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00600-copy.jpg'], url: '/uniforms/combat/crpf-cotton-combat-uniform-for-sub-inspector', category: 'uniforms' },
  { id: 'combat-uniform-ssb-new-pattern', name: "Combat Uniform Ssb New Pattern", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00745.jpg'], url: '/uniforms/combat/combat-uniform-ssb-new-pattern', category: 'uniforms' },
  { id: 'ssb-us-pattern-combat-uniform', name: "Ssb Us Pattern Combat Uniform", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00760.jpg'], url: '/uniforms/combat/ssb-us-pattern-combat-uniform', category: 'uniforms' },
  { id: 'crpf-khaki-uniform-by-ajanta-oswal-super-premium-trovine', name: "Crpf Khaki Uniform By Ajanta Oswal Super Premium Trovine", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00575-copy.jpg'], url: '/uniforms/crpf/crpf-khaki-uniform-by-ajanta-oswal-super-premium-trovine', category: 'uniforms' },
  { id: 'crpf-khaki-uniform-oswal-ajanta', name: "Crpf Khaki Uniform Oswal Ajanta", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00578-copy-scaled.jpg'], url: '/uniforms/crpf/crpf-khaki-uniform-oswal-ajanta', category: 'uniforms' },
  { id: 'bsf-khaki-uniform-vimal-saphire-matty', name: "Bsf Khaki Uniform Vimal Saphire Matty", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00510.jpg'], url: '/uniforms/bsf/bsf-khaki-uniform-vimal-saphire-matty', category: 'uniforms' },
  { id: 'bsf-khaki-uniform-vimal-super-valiant-trovine', name: "Bsf Khaki Uniform Vimal Super Valiant Trovine", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00531.jpg'], url: '/uniforms/bsf/bsf-khaki-uniform-vimal-super-valiant-trovine', category: 'uniforms' },
  { id: 'bsf-khaki-uniform-graviera', name: "Bsf Khaki Uniform Graviera", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00468-scaled.jpg'], url: '/uniforms/bsf/bsf-khaki-uniform-graviera', category: 'uniforms' },
  { id: 'bsf-khaki-uniform-raymond', name: "Bsf Khaki Uniform Raymond", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00494.jpg'], url: '/uniforms/bsf/bsf-khaki-uniform-raymond', category: 'uniforms' },
  { id: 'bsf-khaki-uniform-vimal-super-premium-trovine', name: "Bsf Khaki Uniform Vimal Super Premium Trovine", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00496-scaled.jpg'], url: '/uniforms/bsf/bsf-khaki-uniform-vimal-super-premium-trovine', category: 'uniforms' },
  { id: 'bsf-khaki-uniform-vimal-super-trovine-valiant', name: "Bsf Khaki Uniform Vimal Super Trovine Valiant", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00543.jpg'], url: '/uniforms/bsf/bsf-khaki-uniform-vimal-super-trovine-valiant', category: 'uniforms' },
  { id: 'bsf-khaki-uniform-greviera-2', name: "Bsf Khaki Uniform Greviera 2", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00493.jpg'], url: '/uniforms/bsf/bsf-khaki-uniform-greviera-2', category: 'uniforms' },
  { id: 'bsf-khaki-uniform-raymond-2', name: "Bsf Khaki Uniform Raymond 2", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00498.jpg'], url: '/uniforms/bsf/bsf-khaki-uniform-raymond-2', category: 'uniforms' },
  { id: 'police-khaki-uniform-by-vimal-super-trovine', name: "Police Khaki Uniform By Vimal Super Trovine", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00668-copy.jpg'], url: '/uniforms/police/police-khaki-uniform-by-vimal-super-trovine', category: 'uniforms' },
  { id: 'police-khaki-uniform-vimal-super-trovine', name: "Police Khaki Uniform Vimal Super Trovine", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00631-copy.jpg'], url: '/uniforms/police/police-khaki-uniform-vimal-super-trovine', category: 'uniforms' },
  { id: 'police-khaki-uniform-vimal-premium-trovine-light-color', name: "Police Khaki Uniform Vimal Premium Trovine Light Color", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00641-copy.jpg'], url: '/uniforms/police/police-khaki-uniform-vimal-premium-trovine-light-color', category: 'uniforms' },
  { id: 'police-uniform-by-vimal-super-trovine', name: "Police Uniform By Vimal Super Trovine", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00682-copy.jpg'], url: '/uniforms/police/police-uniform-by-vimal-super-trovine', category: 'uniforms' },
  { id: 'police-stretchable-khaki-uniform', name: "Police Stretchable Khaki Uniform", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00690-scaled.jpg'], url: '/uniforms/police/police-stretchable-khaki-uniform', category: 'uniforms' },
  { id: 'police-khaki-uniform-vimal-super-fabric', name: "Police Khaki Uniform Vimal Super Fabric", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00667-copy-scaled.jpg'], url: '/uniforms/police/police-khaki-uniform-vimal-super-fabric', category: 'uniforms' },
  { id: 'police-stretchable-khaki-uniform-by-vimal-officer-stretch-fit', name: "Police Stretchable Khaki Uniform By Vimal Officer Stretch Fit", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00693.jpg'], url: '/uniforms/police/police-stretchable-khaki-uniform-by-vimal-officer-stretch-fit', category: 'uniforms' },
  { id: 'police-khaki-uniform-by-vimal-premium-trovine', name: "Police Khaki Uniform By Vimal Premium Trovine", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00653-copy.jpg'], url: '/uniforms/police/police-khaki-uniform-by-vimal-premium-trovine', category: 'uniforms' },
  { id: 'police-khaki-uniform-by-vimal-sapphire', name: "Police Khaki Uniform By Vimal Sapphire", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00554.jpg'], url: '/uniforms/police/police-khaki-uniform-by-vimal-sapphire', category: 'uniforms' },
  { id: 'police-khaki-uniform-premium', name: "Police Khaki Uniform Premium", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00651-copy-scaled.jpg'], url: '/uniforms/police/police-khaki-uniform-premium', category: 'uniforms' },
  { id: 'police-khaki-uniform-premium-trovine', name: "Police Khaki Uniform Premium Trovine", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00640-copy-scaled.jpg'], url: '/uniforms/police/police-khaki-uniform-premium-trovine', category: 'uniforms' },
  { id: 'police-uniform-reymonds', name: "Police Uniform Reymonds", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00575-copy.jpg'], url: '/uniforms/police/police-uniform-reymonds', category: 'uniforms' },
  { id: 'police-khaki-uniform-by-siyaram-matte', name: "Police Khaki Uniform By Siyaram Matte", price: 3000, badge: 'Uniforms', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00565.jpg'], url: '/uniforms/police/police-khaki-uniform-by-siyaram-matte', category: 'uniforms' },
  // T-SHIRTS
  { id: 'white-t-shirt-cotton-2', name: "White T Shirt Cotton 2", price: 3000, badge: 'T-Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00702.jpg'], url: '/t-shirts/white-t-shirt-cotton-2', category: 't-shirts' },
  { id: 'white-t-shirt-cotton-matty', name: "White T Shirt Cotton Matty", price: 3000, badge: 'T-Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00709-scaled.jpg'], url: '/t-shirts/white-t-shirt-cotton-matty', category: 't-shirts' },
  { id: 'white-cotton-t-shirt1', name: "White Cotton T Shirt1", price: 3000, badge: 'T-Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00717-scaled.jpg'], url: '/t-shirts/white-cotton-t-shirt1', category: 't-shirts' },
  { id: 'white-t-shirt-cotton', name: "White T Shirt Cotton", price: 3000, badge: 'T-Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00711.jpg'], url: '/t-shirts/white-t-shirt-cotton', category: 't-shirts' },
  { id: 'white-premium-cotton-t-shirt', name: "White Premium Cotton T Shirt", price: 3000, badge: 'T-Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00720.jpg'], url: '/t-shirts/white-premium-cotton-t-shirt', category: 't-shirts' },
  { id: 'whit-t-shirt-cotton-matty', name: "Whit T Shirt Cotton Matty", price: 3000, badge: 'T-Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00711.jpg'], url: '/t-shirts/whit-t-shirt-cotton-matty', category: 't-shirts' },
  { id: 'white-cotton-t-shirt', name: "White Cotton T Shirt", price: 3000, badge: 'T-Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/CKS00709-scaled.jpg'], url: '/t-shirts/white-cotton-t-shirt', category: 't-shirts' },
  { id: 'crpf-cotton-combat-pt-t-shirt-olive-green-100-cotton-for-daily-pt-training', name: "Crpf Cotton Combat Pt T Shirt Olive Green 100 Cotton For Daily Pt Training", price: 3000, badge: 'T-Shirts', sizes: ['38','40','42','44'], images: ['https://media.treyondworld.com/2024/05/Best-wardi-shop-for-army-police.png'], url: '/t-shirts/crpf-cotton-combat-pt-t-shirt-olive-green-100-cotton-for-daily-pt-training', category: 't-shirts' },
];

// ===== RENDER PRODUCT GRID =====
function renderProductGrid(containerId, products) {
  const container = document.getElementById(containerId);
  if (!container) return;
  container.innerHTML = products.filter(Boolean).map(p => `
    <div class="product-card reveal">
      <a href="${p.url}">
        <div class="product-card-img-wrap">
          <img class="product-card-img" src="${p.images[0]}" alt="${p.name}" loading="lazy">
          <div class="product-card-badges">${p.badge ? `<span class="badge">${p.badge}</span>` : ''}</div>
          <div class="product-card-actions">
            <button class="product-action-btn" onclick="event.preventDefault();Wishlist.toggle('${p.id}');this.style.color=Wishlist.has('${p.id}')?'#e11d48':''" title="Wishlist">
              <svg fill="none" stroke="currentColor" viewBox="0 0 24 24" width="16" height="16"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"/></svg>
            </button>
            <button class="product-action-btn" onclick="event.preventDefault();openQuickView('${p.id}')" title="Quick View">
              <svg fill="none" stroke="currentColor" viewBox="0 0 24 24" width="16" height="16"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/></svg>
            </button>
          </div>
          <button class="product-card-quick" onclick="event.preventDefault();Cart.add({id:'${p.id}',name:'${p.name}',price:${p.price},image:'${p.images[0]}',variant:'Default'})">Quick Add</button>
        </div>
      </a>
      <a href="${p.url}">
        <div class="product-card-info">
          <div class="product-card-name">${p.name}</div>
          <div class="product-card-price"><span class="product-price">${formatPrice(p.price)}</span></div>
        </div>
      </a>
    </div>`).join('');
  initScrollReveal();
}

document.addEventListener('DOMContentLoaded', () => {
  initHeroSlider();
  initTestimonialsSlider();
  initNewsletter();

  if (document.getElementById('uniform-page') || window.location.pathname.includes('uniform')) {
    renderProductGrid('uniforms-featured-grid', PRODUCTS_DATA.filter(p => p.category === 'uniforms'));
    renderProductGrid('combat-featured-grid', PRODUCTS_DATA.filter(p => p.category === 'combat-uniforms'));
    renderProductGrid('tshirts-featured-grid', PRODUCTS_DATA.filter(p => p.category === 't-shirts'));
    renderProductGrid('trending-grid', PRODUCTS_DATA.filter(p => ['u1','u4','u2','tshirt-01'].includes(p.id)));
  } else {
    // 7 category grids
    renderProductGrid('shirts-grid', PRODUCTS_DATA.filter(p => p.category === 'shirts').slice(0, 4));
    renderProductGrid('check-shirts-grid', PRODUCTS_DATA.filter(p => p.category === 'check-shirts').slice(0, 4));
    renderProductGrid('strap-shirts-grid', PRODUCTS_DATA.filter(p => p.category === 'strap-shirts').slice(0, 4));
    renderProductGrid('trousers-grid', PRODUCTS_DATA.filter(p => p.category === 'trousers').slice(0, 4));
    renderProductGrid('blazers-grid', PRODUCTS_DATA.filter(p => p.category === 'blazers').slice(0, 4));
    renderProductGrid('modi-grid', PRODUCTS_DATA.filter(p => p.category === 'modi-jacket').slice(0, 4));
    renderProductGrid('suits-grid', PRODUCTS_DATA.filter(p => p.category === 'suits').slice(0, 4));
  }
});
